export interface IDyo{
    id:number;
    name?:string;
    img?:string;
    stock?:string;
    value?:string;
    color?:string;
    product?:string;
    number?:number;
    productNumber?:string;
    order?:string;
    date?:any;
    status?:string;
    customer?:string;
    extraSmall?:number;
    small?:number;
    medium?:number;
    large?:number;
    doubleExtraLarge?:number;
    thripleExtraLarge?:number;
    total?:number;
    active:boolean;
}